server:
   servlet:
      contextPath: /CarWashAgent
spring:
   jpa:
      show-sql: true
      open-in-view: false
      hibernate:
         ddl-auto: validate
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
   datasource:
      hikari:
         connectionTimeout: 20000
         maximumPoolSize: 5
      url: jdbc:postgresql://database:5432/backend
      